# Generated by Django 5.0.6 on 2024-06-06 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0002_patient_delete_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doa',
            field=models.DateField(default=datetime.datetime(2024, 6, 6, 16, 31, 2, 452104, tzinfo=datetime.timezone.utc)),
        ),
    ]
