# Generated by Django 5.0.6 on 2024-06-06 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0003_alter_patient_doa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doa',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
