# Generated by Django 5.0.6 on 2024-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0004_alter_patient_doa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='discharged_hospital',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharged_therapies',
            field=models.DateField(blank=True),
        ),
    ]
