# Generated by Django 5.0.6 on 2024-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0005_alter_patient_discharged_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.IntegerField(blank=True),
        ),
    ]
