# Generated by Django 5.0.6 on 2024-06-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0006_alter_patient_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='discharged_hospital',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharged_therapies',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
