# Generated by Django 5.0.6 on 2024-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0008_patient_location_alter_patient_mrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_time',
            field=models.IntegerField(default=0),
        ),
    ]
