# Generated by Django 5.0.6 on 2024-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0010_remove_patient_borough_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FAL', 'Fall'), ('NEU', 'Neuro'), ('GEN', 'Generally unwell'), ('MEH', 'Mental health'), ('ORT', 'Orthopaedic'), ('RES', 'Respiratory')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borough', models.CharField(choices=[('GRE', 'Greenwich'), ('BEX', 'Bexley'), ('LEW', 'Lewisham'), ('HOM', 'Homerton'), ('OOB', 'Out of borough')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Discharge_locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('HOM', 'Home'), ('WAR', 'Ward'), ('ICB', 'Rehab unit'), ('PLC', 'Placement')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[('CAR', 'Cardiology'), ('COE', 'Geriatric'), ('PED', 'Paediatric'), ('ONC', 'Oncology'), ('ORT', 'Orthopaedic'), ('NEU', 'Neurology'), ('RES', 'Respiratory')], max_length=50)),
            ],
        ),
    ]
