# Generated by Django 5.0.6 on 2024-06-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0011_admissionreason_borough_discharge_locations_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='borough',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edcaseload.borough'),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edcaseload.discharge_locations'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edcaseload.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edcaseload.admissionreason'),
        ),
    ]
