# Generated by Django 5.0.6 on 2024-06-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0012_patient_borough_patient_discharge_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borough',
            old_name='Borough',
            new_name='borough',
        ),
    ]
