# Generated by Django 5.0.6 on 2024-06-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0013_rename_borough_borough_borough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionreason',
            name='reason',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Neuro', 'Neuro'), ('Generally unwell', 'Generally unwell'), ('Mental Health', 'Mental health'), ('Orthopaedic', 'Orthopaedic'), ('Respiratory', 'Respiratory')], max_length=50),
        ),
        migrations.AlterField(
            model_name='borough',
            name='borough',
            field=models.CharField(choices=[('Greenwich', 'Greenwich'), ('Bexley', 'Bexley'), ('Lewisham', 'Lewisham'), ('Homerton', 'Homerton'), ('Out of borough', 'Out of borough')], max_length=20),
        ),
        migrations.AlterField(
            model_name='discharge_locations',
            name='location',
            field=models.CharField(choices=[('Home', 'Home'), ('Ward', 'Ward'), ('Rehab unit', 'Rehab unit'), ('Placement', 'Placement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Geriatric', 'Geriatric'), ('Paediatric', 'Paediatric'), ('Oncology', 'Oncology'), ('Orthopaedic', 'Orthopaedic'), ('Neurology', 'Neurology'), ('Respiratory', 'Respiratory')], max_length=50),
        ),
    ]
