# Generated by Django 5.0.6 on 2024-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcaseload', '0014_alter_admissionreason_reason_alter_borough_borough_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discharge_locations',
            new_name='Discharge_location',
        ),
        migrations.AddField(
            model_name='patient',
            name='referral',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
